from __future__ import annotations

from pathlib import Path

from sqlalchemy import delete, func, select
from sqlalchemy.orm import Session

from app.db.models import Candidate, CandidateStatus, Episode, EpisodeStatus, Shot, TranscriptSegment
from app.services.storage_service import write_placeholder


MOCK_TRANSCRIPT = [
    "I thought this meeting was supposed to help us.",
    "It is helping. Now we know how bad the problem really is.",
    "That is the most aggressive way to say stay calm.",
    "Exactly. Which is why this scene works as a short.",
    "The audience understands the tension in one line.",
    "Then we turn it into commentary instead of raw recap.",
    "That gives us a hook, body, and a clean payoff.",
    "And it keeps the clip short enough for a first draft.",
]


def ingest_episode_step(db: Session, episode_id: str) -> dict:
    episode = db.get(Episode, episode_id)
    if episode is None:
        raise ValueError("Episode not found")
    if not Path(episode.source_video_path).exists():
        raise FileNotFoundError("Source video file is missing")

    episode.status = EpisodeStatus.PROCESSING.value
    episode.duration_seconds = episode.duration_seconds or 42.0
    episode.fps = episode.fps or 23.976
    episode.width = episode.width or 1920
    episode.height = episode.height or 1080
    episode.metadata_json = {
        **(episode.metadata_json or {}),
        "ingest_mode": "mock",
        "source_verified": True,
    }
    db.add(episode)
    db.commit()

    return {"episode_id": episode.id}


def transcode_proxy_step(db: Session, payload: dict) -> dict:
    episode = db.get(Episode, payload["episode_id"])
    if episode is None:
        raise ValueError("Episode not found")

    episode.proxy_video_path = write_placeholder(
        episode.id,
        ["proxy", "proxy.mp4"],
        "mock proxy artifact generated by transcode_proxy",
    )
    episode.audio_path = write_placeholder(
        episode.id,
        ["audio", "audio.wav"],
        "mock audio artifact generated by transcode_proxy",
    )
    db.add(episode)
    db.commit()
    return payload


def detect_shots_step(db: Session, payload: dict) -> dict:
    episode_id = payload["episode_id"]
    db.execute(delete(Shot).where(Shot.episode_id == episode_id))
    for index in range(8):
        start_time = round(index * 5.0, 3)
        end_time = round(start_time + 4.2, 3)
        thumbnail_path = write_placeholder(
            episode_id,
            ["shots", f"{index + 1:02d}.jpg"],
            f"mock thumbnail for shot {index + 1}",
        )
        db.add(
            Shot(
                episode_id=episode_id,
                shot_index=index + 1,
                start_time=start_time,
                end_time=end_time,
                thumbnail_path=thumbnail_path,
            )
        )
    db.commit()
    return payload


def extract_or_generate_transcript_step(db: Session, payload: dict) -> dict:
    episode_id = payload["episode_id"]
    db.execute(delete(TranscriptSegment).where(TranscriptSegment.episode_id == episode_id))
    for index, line in enumerate(MOCK_TRANSCRIPT):
        start_time = round(index * 5.0 + 0.5, 3)
        end_time = round(start_time + 3.2, 3)
        db.add(
            TranscriptSegment(
                episode_id=episode_id,
                segment_index=index + 1,
                start_time=start_time,
                end_time=end_time,
                text=line,
                speaker_label=f"spk_{(index % 2) + 1}",
            )
        )
    db.commit()
    return payload


def compute_signals_step(db: Session, payload: dict) -> dict:
    episode = db.get(Episode, payload["episode_id"])
    if episode is None:
        raise ValueError("Episode not found")
    episode.metadata_json = {
        **(episode.metadata_json or {}),
        "signals": {
            "tension_regions": [[5.0, 15.0], [20.0, 31.0]],
            "commentary_friendly": True,
        },
    }
    db.add(episode)
    db.commit()
    return payload


def generate_candidates_step(db: Session, payload: dict) -> dict:
    episode_id = payload["episode_id"]
    db.execute(delete(Candidate).where(Candidate.episode_id == episode_id))

    candidate_specs = [
        {
            "title_hint": "The meeting line that sounds calm but is not",
            "start_time": 5.0,
            "end_time": 28.0,
            "total_score": 8.9,
            "risk_score": 2.1,
            "risk_level": "low",
        },
        {
            "title_hint": "Why this scene becomes commentary gold",
            "start_time": 10.0,
            "end_time": 33.0,
            "total_score": 8.4,
            "risk_score": 2.6,
            "risk_level": "low",
        },
        {
            "title_hint": "The one line that explains the whole tension",
            "start_time": 15.0,
            "end_time": 37.0,
            "total_score": 8.1,
            "risk_score": 3.1,
            "risk_level": "medium",
        },
    ]

    for index, spec in enumerate(candidate_specs, start=1):
        db.add(
            Candidate(
                episode_id=episode_id,
                candidate_index=index,
                type="context_commentary",
                status=CandidateStatus.GENERATED.value,
                title_hint=spec["title_hint"],
                start_time=spec["start_time"],
                end_time=spec["end_time"],
                duration_seconds=round(spec["end_time"] - spec["start_time"], 3),
                total_score=spec["total_score"],
                risk_score=spec["risk_score"],
                risk_level=spec["risk_level"],
                scores_json={
                    "total_score": spec["total_score"],
                    "hook_score": round(spec["total_score"] + 0.2, 2),
                    "clarity_score": round(spec["total_score"] - 0.3, 2),
                    "commentary_score": round(spec["total_score"] + 0.1, 2),
                },
                risk_reasons=["mock_pipeline", "commentary_density_high"],
                metadata_json={"generated_by": "mock_analysis"},
            )
        )

    episode = db.get(Episode, episode_id)
    if episode is None:
        raise ValueError("Episode not found")
    episode.status = EpisodeStatus.READY.value
    db.add(episode)
    db.commit()

    candidate_count = db.scalar(select(func.count(Candidate.id)).where(Candidate.episode_id == episode_id))
    return {"episode_id": episode_id, "candidate_count": candidate_count}


def candidate_segments(db: Session, candidate: Candidate) -> list[TranscriptSegment]:
    query = (
        select(TranscriptSegment)
        .where(TranscriptSegment.episode_id == candidate.episode_id)
        .where(TranscriptSegment.start_time <= candidate.end_time)
        .where(TranscriptSegment.end_time >= candidate.start_time)
        .order_by(TranscriptSegment.start_time.asc())
    )
    return list(db.scalars(query))


def candidate_shots(db: Session, candidate: Candidate) -> list[Shot]:
    query = (
        select(Shot)
        .where(Shot.episode_id == candidate.episode_id)
        .where(Shot.start_time <= candidate.end_time)
        .where(Shot.end_time >= candidate.start_time)
        .order_by(Shot.shot_index.asc())
    )
    return list(db.scalars(query))
